import { glossaryEntrySchema, type GlossaryEntry } from './schema'

/**
 * Немецко-русский словарь школьной математики, 6 класс.
 *
 * Отдельная категория operatoren — глаголы-команды из формулировок заданий
 * (Berechne, Begründe, Ordne …). На уровне A1–A2 непонятое задание чаще упирается
 * именно в них, а не в саму математику, поэтому учить их стоит первыми.
 */
const entries: GlossaryEntry[] = [
  /* ---------------------------------------------------------------- числа */
  { id: 'zahl', de: 'Zahl', ru: 'число', article: 'die', plural: 'Zahlen', category: 'zahlen' },
  {
    id: 'natuerliche-zahl',
    de: 'natürliche Zahl',
    ru: 'натуральное число',
    article: 'die',
    plural: 'natürliche Zahlen',
    example: 'Die Zahlen 1, 2, 3 … sind natürliche Zahlen.',
    category: 'zahlen',
  },
  {
    id: 'ganze-zahl',
    de: 'ganze Zahl',
    ru: 'целое число',
    article: 'die',
    plural: 'ganze Zahlen',
    category: 'zahlen',
  },
  {
    id: 'bruch',
    de: 'Bruch',
    ru: 'обыкновенная дробь',
    article: 'der',
    plural: 'Brüche',
    memo: 'От brechen — ломать. Дробь = отломанная часть целого.',
    category: 'zahlen',
  },
  {
    id: 'zaehler',
    de: 'Zähler',
    ru: 'числитель — верхнее число дроби',
    article: 'der',
    plural: 'Zähler',
    memo: 'От zählen — считать. Числитель считает, сколько частей взяли.',
    category: 'zahlen',
  },
  {
    id: 'nenner',
    de: 'Nenner',
    ru: 'знаменатель — нижнее число дроби',
    article: 'der',
    plural: 'Nenner',
    memo: 'От nennen — называть. Знаменатель называет, на сколько частей поделили.',
    category: 'zahlen',
  },
  {
    id: 'dezimalzahl',
    de: 'Dezimalzahl',
    ru: 'десятичная дробь',
    article: 'die',
    plural: 'Dezimalzahlen',
    example: 'Schreibe den Bruch als Dezimalzahl.',
    category: 'zahlen',
  },
  {
    id: 'komma',
    de: 'Komma',
    ru: 'запятая — в немецкой записи отделяет дробную часть: 3,5',
    article: 'das',
    category: 'zahlen',
  },
  {
    id: 'primzahl',
    de: 'Primzahl',
    ru: 'простое число',
    article: 'die',
    plural: 'Primzahlen',
    memo: 'Из простого числа складывается только один прямоугольник — полоска 1 × само число.',
    category: 'zahlen',
  },
  {
    id: 'teiler',
    de: 'Teiler',
    ru: 'делитель',
    article: 'der',
    plural: 'Teiler',
    memo: 'От глагола teilen — делить.',
    category: 'zahlen',
  },
  {
    id: 'vielfaches',
    de: 'Vielfaches',
    ru: 'кратное',
    article: 'das',
    plural: 'Vielfache',
    memo: 'viel — много. Кратное = «много раз по этому числу».',
    category: 'zahlen',
  },
  {
    id: 'ggt',
    de: 'ggT — größter gemeinsamer Teiler',
    ru: 'НОД — наибольший общий делитель',
    memo: 'Три буквы — три слова: größter (наибольший), gemeinsamer (общий), Teiler (делитель).',
    category: 'zahlen',
  },
  {
    id: 'kgv',
    de: 'kgV — kleinstes gemeinsames Vielfaches',
    ru: 'НОК — наименьшее общее кратное',
    memo: 'Так же по первым буквам: kleinstes (наименьшее), gemeinsames (общее), Vielfaches (кратное).',
    category: 'zahlen',
  },
  {
    id: 'prozent',
    de: 'Prozent',
    ru: 'процент',
    article: 'das',
    example: '25 % von 80 sind 20.',
    category: 'zahlen',
  },
  {
    id: 'negative-zahl',
    de: 'negative Zahl',
    ru: 'отрицательное число',
    article: 'die',
    category: 'zahlen',
  },
  {
    id: 'teilbar',
    de: 'teilbar',
    ru: 'делится без остатка',
    example: 'Ist 56 durch 7 teilbar?',
    memo: 'teilen + -bar, как в английском -able: «делимый».',
    category: 'zahlen',
  },
  {
    id: 'teiler-menge',
    de: 'Teiler-Menge',
    ru: 'множество делителей: T₄ = {1; 2; 4}',
    article: 'die',
    example: 'Gib die Teiler-Menge von 28 an.',
    memo: 'Menge — множество, набор. Отсюда и буква T со скобками.',
    category: 'zahlen',
  },
  {
    id: 'vielfachen-menge',
    de: 'Vielfachen-Menge',
    ru: 'множество кратных: V₆ = {6; 12; 18; …}',
    article: 'die',
    example: 'Ergänze die Vielfachen-Menge im Heft.',
    memo: 'Та же Menge, только для кратных: буква V.',
    category: 'zahlen',
  },
  {
    id: 'gerade',
    de: 'gerade Zahl',
    ru: 'чётное число — делится на 2',
    article: 'die',
    memo: 'gerade значит ещё и «прямой», «ровный». Чётное — ровно делится пополам.',
    category: 'zahlen',
  },
  {
    id: 'ungerade',
    de: 'ungerade Zahl',
    ru: 'нечётное число',
    article: 'die',
    category: 'zahlen',
  },
  {
    id: 'quersumme',
    de: 'Quersumme',
    ru: 'сумма цифр числа: у 436 это 4 + 3 + 6 = 13',
    article: 'die',
    example: 'Berechne die Quersumme.',
    memo: 'quer — поперёк. Складываешь цифры «поперёк» числа.',
    category: 'zahlen',
  },
  {
    id: 'einerziffer',
    de: 'Einerziffer',
    ru: 'последняя цифра числа',
    article: 'die',
    example: 'Markiere die Einerziffer der Zahl.',
    memo: 'Einer — единицы. Цифра, стоящая в разряде единиц.',
    category: 'zahlen',
  },
  {
    id: 'ziffer',
    de: 'Ziffer',
    ru: 'цифра — знак, из которых состоит число',
    article: 'die',
    plural: 'Ziffern',
    category: 'zahlen',
  },
  {
    id: 'bruchstrich',
    de: 'Bruchstrich',
    ru: 'дробная черта',
    article: 'der',
    memo: 'Strich — черта. Та самая черта, что ломает целое.',
    category: 'zahlen',
  },
  {
    id: 'das-ganze',
    de: 'das Ganze',
    ru: 'целое — то, что делят на части',
    category: 'zahlen',
  },
  {
    id: 'echter-bruch',
    de: 'echter Bruch',
    ru: 'правильная дробь — числитель меньше знаменателя',
    article: 'der',
    category: 'zahlen',
  },
  {
    id: 'unechter-bruch',
    de: 'unechter Bruch',
    ru: 'неправильная дробь — числитель не меньше знаменателя',
    article: 'der',
    category: 'zahlen',
  },
  {
    id: 'gemischte-zahl',
    de: 'gemischte Zahl',
    ru: 'смешанное число: 1¾',
    article: 'die',
    category: 'zahlen',
  },
  {
    id: 'zahlenstrahl',
    de: 'Zahlenstrahl',
    ru: 'числовой луч',
    article: 'der',
    example: 'Trage die Brüche am Zahlenstrahl ein.',
    category: 'zahlen',
  },
  {
    id: 'gleichwertig',
    de: 'gleichwertig',
    ru: 'равные по значению — стоят в одной точке луча',
    category: 'zahlen',
  },

  /* -------------------------------------------------------------- действия */
  { id: 'addieren', de: 'addieren', ru: 'складывать', category: 'rechnen' },
  { id: 'subtrahieren', de: 'subtrahieren', ru: 'вычитать', category: 'rechnen' },
  { id: 'multiplizieren', de: 'multiplizieren', ru: 'умножать', category: 'rechnen' },
  { id: 'dividieren', de: 'dividieren', ru: 'делить', category: 'rechnen' },
  {
    id: 'summe',
    de: 'Summe',
    ru: 'сумма — результат сложения',
    article: 'die',
    category: 'rechnen',
  },
  {
    id: 'differenz',
    de: 'Differenz',
    ru: 'разность — результат вычитания',
    article: 'die',
    category: 'rechnen',
  },
  {
    id: 'produkt',
    de: 'Produkt',
    ru: 'произведение — результат умножения',
    article: 'das',
    category: 'rechnen',
  },
  {
    id: 'quotient',
    de: 'Quotient',
    ru: 'частное — результат деления',
    article: 'der',
    category: 'rechnen',
  },
  {
    id: 'kuerzen',
    de: 'kürzen',
    ru: 'сокращать дробь',
    example: 'Kürze den Bruch so weit wie möglich.',
    memo: 'kurz — короткий. Сокращая, делаешь запись короче.',
    category: 'rechnen',
  },
  {
    id: 'erweitern',
    de: 'erweitern',
    ru: 'расширить дробь — умножить числитель и знаменатель на одно и то же число',
    memo: 'weit — широкий. Расширяя, делаешь числа крупнее.',
    category: 'rechnen',
  },
  { id: 'runden', de: 'runden', ru: 'округлять', category: 'rechnen' },
  {
    id: 'klammer',
    de: 'Klammer',
    ru: 'скобка',
    article: 'die',
    plural: 'Klammern',
    category: 'rechnen',
  },
  {
    id: 'potenz',
    de: 'Potenz',
    ru: 'степень',
    article: 'die',
    plural: 'Potenzen',
    category: 'rechnen',
  },
  {
    id: 'term',
    de: 'Term',
    ru: 'выражение',
    article: 'der',
    plural: 'Terme',
    category: 'rechnen',
  },
  {
    id: 'gleichung',
    de: 'Gleichung',
    ru: 'уравнение',
    article: 'die',
    plural: 'Gleichungen',
    category: 'rechnen',
  },

  {
    id: 'gleichnamig',
    de: 'gleichnamig',
    ru: 'с одинаковым знаменателем',
    memo: 'gleich — одинаковый, Name — имя. У дробей «одинаковое имя» — знаменатель.',
    category: 'rechnen',
  },
  {
    id: 'ungleichnamig',
    de: 'ungleichnamig',
    ru: 'с разными знаменателями',
    category: 'rechnen',
  },
  {
    id: 'gemeinsamer-nenner',
    de: 'gemeinsamer Nenner',
    ru: 'общий знаменатель',
    article: 'der',
    category: 'rechnen',
  },
  {
    id: 'hauptnenner',
    de: 'Hauptnenner',
    ru: 'наименьший общий знаменатель — это НОК знаменателей',
    article: 'der',
    category: 'rechnen',
  },
  {
    id: 'erweiterungszahl',
    de: 'Erweiterungszahl',
    ru: 'число, на которое умножили при расширении дроби',
    article: 'die',
    category: 'rechnen',
  },
  {
    id: 'kuerzungszahl',
    de: 'Kürzungszahl',
    ru: 'число, на которое сократили дробь',
    article: 'die',
    category: 'rechnen',
  },
  {
    id: 'primfaktorzerlegung',
    de: 'Primfaktorzerlegung',
    ru: 'разложение на простые множители: 18 = 2 · 3 · 3',
    article: 'die',
    category: 'rechnen',
  },

  /* ------------------------------------------------------------- геометрия */
  {
    id: 'rechteck',
    de: 'Rechteck',
    ru: 'прямоугольник',
    article: 'das',
    plural: 'Rechtecke',
    category: 'geometrie',
  },
  {
    id: 'quadrat',
    de: 'Quadrat',
    ru: 'квадрат',
    article: 'das',
    plural: 'Quadrate',
    category: 'geometrie',
  },
  {
    id: 'dreieck',
    de: 'Dreieck',
    ru: 'треугольник',
    article: 'das',
    plural: 'Dreiecke',
    category: 'geometrie',
  },
  {
    id: 'kreis',
    de: 'Kreis',
    ru: 'круг, окружность',
    article: 'der',
    plural: 'Kreise',
    category: 'geometrie',
  },
  {
    id: 'umfang',
    de: 'Umfang',
    ru: 'периметр',
    article: 'der',
    example: 'Berechne den Umfang des Rechtecks.',
    category: 'geometrie',
  },
  {
    id: 'flaecheninhalt',
    de: 'Flächeninhalt',
    ru: 'площадь',
    article: 'der',
    example: 'Berechne den Flächeninhalt.',
    category: 'geometrie',
  },
  { id: 'volumen', de: 'Volumen', ru: 'объём', article: 'das', category: 'geometrie' },
  {
    id: 'winkel',
    de: 'Winkel',
    ru: 'угол',
    article: 'der',
    plural: 'Winkel',
    category: 'geometrie',
  },
  {
    id: 'seite',
    de: 'Seite',
    ru: 'сторона',
    article: 'die',
    plural: 'Seiten',
    category: 'geometrie',
  },
  {
    id: 'koordinatensystem',
    de: 'Koordinatensystem',
    ru: 'координатная плоскость',
    article: 'das',
    category: 'geometrie',
  },
  { id: 'massstab', de: 'Maßstab', ru: 'масштаб', article: 'der', category: 'geometrie' },

  /* -------------------------------------- операторы: глаголы в заданиях */
  {
    id: 'berechne',
    de: 'Berechne …',
    ru: 'Вычисли … — нужен только результат',
    category: 'operatoren',
  },
  { id: 'bestimme', de: 'Bestimme …', ru: 'Определи, найди …', category: 'operatoren' },
  { id: 'zeichne', de: 'Zeichne …', ru: 'Начерти …', category: 'operatoren' },
  {
    id: 'begruende',
    de: 'Begründe …',
    ru: 'Обоснуй — объясни почему. Нужен текст, а не только ответ',
    category: 'operatoren',
  },
  { id: 'erklaere', de: 'Erkläre …', ru: 'Объясни …', category: 'operatoren' },
  { id: 'vergleiche', de: 'Vergleiche …', ru: 'Сравни …', category: 'operatoren' },
  {
    id: 'ordne',
    de: 'Ordne … der Größe nach',
    ru: 'Расставь … по возрастанию',
    category: 'operatoren',
  },
  {
    id: 'schaetze',
    de: 'Schätze …',
    ru: 'Прикинь примерно — без точного вычисления',
    category: 'operatoren',
  },
  { id: 'ergaenze', de: 'Ergänze …', ru: 'Дополни, вставь пропущенное …', category: 'operatoren' },
  {
    id: 'kreuze-an',
    de: 'Kreuze an',
    ru: 'Отметь крестиком — выбери вариант',
    category: 'operatoren',
  },
  { id: 'finde', de: 'Finde …', ru: 'Найди …', category: 'operatoren' },
  {
    id: 'nenne',
    de: 'Nenne …',
    ru: 'Назови … — достаточно перечислить, без вычислений на бумаге',
    category: 'operatoren',
  },
  {
    id: 'gib-an',
    de: 'Gib … an',
    ru: 'Укажи, выпиши …',
    example: 'Gib die Teiler-Menge von 28 an.',
    category: 'operatoren',
  },
  {
    id: 'verbinde',
    de: 'Verbinde …',
    ru: 'Соедини линиями …',
    category: 'operatoren',
  },
  {
    id: 'markiere',
    de: 'Markiere …',
    ru: 'Отметь, выдели …',
    category: 'operatoren',
  },
  {
    id: 'faerbe',
    de: 'Färbe …',
    ru: 'Закрась …',
    category: 'operatoren',
  },
  {
    id: 'notiere',
    de: 'Notiere …',
    ru: 'Запиши …',
    category: 'operatoren',
  },
  {
    id: 'ueberpruefe',
    de: 'Überprüfe …',
    ru: 'Проверь …',
    category: 'operatoren',
  },
  {
    id: 'uebertrage',
    de: 'Übertrage ins Heft',
    ru: 'Перепиши в тетрадь',
    category: 'operatoren',
  },
  {
    id: 'richtig-oder-falsch',
    de: 'Richtig oder falsch?',
    ru: 'Верно или неверно?',
    category: 'operatoren',
  },
  {
    id: 'wahr-falsch',
    de: 'wahr / falsch',
    ru: 'истина / ложь — в таблицах с галочками',
    category: 'operatoren',
  },

  /* ----------------------------------------------------------------- общее */
  {
    id: 'aufgabe',
    de: 'Aufgabe',
    ru: 'задание, задача',
    article: 'die',
    plural: 'Aufgaben',
    category: 'allgemein',
  },
  {
    id: 'loesung',
    de: 'Lösung',
    ru: 'решение, ответ',
    article: 'die',
    plural: 'Lösungen',
    category: 'allgemein',
  },
  {
    id: 'ergebnis',
    de: 'Ergebnis',
    ru: 'результат',
    article: 'das',
    plural: 'Ergebnisse',
    category: 'allgemein',
  },
  {
    id: 'einheit',
    de: 'Einheit',
    ru: 'единица измерения: cm, kg, €',
    article: 'die',
    plural: 'Einheiten',
    category: 'allgemein',
  },
  { id: 'ungefaehr', de: 'ungefähr', ru: 'примерно, около', category: 'allgemein' },
]

/** Словарь после валидации схемой — опечатка в записи падает при загрузке. */
export const GLOSSARY: GlossaryEntry[] = entries.map((entry) => glossaryEntrySchema.parse(entry))

const byId = new Map(GLOSSARY.map((entry) => [entry.id, entry]))

export function getTerm(id: string): GlossaryEntry | undefined {
  return byId.get(id)
}

export function hasTerm(id: string): boolean {
  return byId.has(id)
}

/** Порядок разделов на странице словаря: сначала то, что мешает читать задания. */
export const GLOSSARY_CATEGORIES: { id: GlossaryEntry['category']; ru: string }[] = [
  { id: 'operatoren', ru: 'Слова-команды в заданиях' },
  { id: 'zahlen', ru: 'Числа и дроби' },
  { id: 'rechnen', ru: 'Действия и вычисления' },
  { id: 'geometrie', ru: 'Геометрия' },
  { id: 'allgemein', ru: 'Общие слова' },
]
